apiVersion: v1
kind: Service
metadata:
  name: nodejs_service
spec:
  selector:
    app: nodejs_app
  ports:
    - protocol: TCP
      port: 80  # Port to expose on the service
      targetPort: 80  # Port your application listens on in the pods
  type: ClusterIP
