apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80  # Port to expose on the service
      targetPort: 3000  # Port your application listens on in the pods
  type: ClusterIP
