apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: mynode-containers
          image: amodsingh25/nodejsapp:latest  # Your Docker image and version
          ports:
            - containerPort: 3000  # Port your application listens on
